INSERT INTO ROOM_DETAILS(ROOM_NAME, CAPACITY) VALUES('AMAZE','3');
INSERT INTO ROOM_DETAILS(ROOM_NAME, CAPACITY) VALUES('BEAUTY','7');
INSERT INTO ROOM_DETAILS(ROOM_NAME, CAPACITY) VALUES('INSPIRE','12');
INSERT INTO ROOM_DETAILS(ROOM_NAME, CAPACITY) VALUES('STRIVE','20');

INSERT INTO MAINTENANCE_TIME(START_TIME, END_TIME) VALUES('09:00:00', '09:15:00');
INSERT INTO MAINTENANCE_TIME(START_TIME, END_TIME) VALUES('13:00:00', '13:15:00');
INSERT INTO MAINTENANCE_TIME(START_TIME, END_TIME) VALUES('17:00:00', '17:15:00');